## Categorical Encodidng

In this challenge, we will touch on another data preparation task that you should be aware of. This task revolves around dealing with "Categorical" variables. As you already know by now, Machine Learning models are based on mathematical equations. If the underlying data set contains categorical data, then the categorical variables needed to be converted into numbers since a mathematical equation only contains numbers. 

The data set used in Coding Challenge #1 contains 2 categorical variables i.e. 'Cities in East Bay' and 'Own Home?'. The first categorical variable contains 3 categories i.e. 'Pleasanton', 'Walnut Creek' and 'Dublin' and the second categorical variable contains 2 categories i.e. 'Yes' and 'No.

Ask? Encode the 'Cities in Bay Area' categorical variable into numbers.

*Hint*: Utilize the LabelEncoder class from the sklearn.preprocessing page

*Additional Resource*: http://pbpython.com/categorical-encoding.html

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

dataset = pd.read_csv('https://www.dropbox.com/s/91tthp8h6hgxzi6/Data-CodeChallenge1.csv?raw=1')
dataset

Cities in East Bay   Age    Salary Own Home?
0         Pleasanton  44.0  172000.0        No
1       Walnut Creek  27.0  148000.0       Yes
2             Dublin  30.0  154000.0        No
3       Walnut Creek  38.0  161000.0        No
4             Dublin  40.0       NaN       Yes
5         Pleasanton  35.0  158000.0       Yes
6       Walnut Creek   NaN  152000.0        No
7         Pleasanton  48.0  179000.0       Yes
8             Dublin  50.0  183000.0        No
9         Pleasanton  37.0  167000.0       Yes

In [2]:
dataset['Cities in East Bay'] = LabelEncoder().fit_transform(dataset['Cities in East Bay'])
dataset['Own Home?'] = LabelEncoder().fit_transform(dataset['Own Home?'])
dataset

Cities in East Bay   Age    Salary  Own Home?
0                   1  44.0  172000.0          0
1                   2  27.0  148000.0          1
2                   0  30.0  154000.0          0
3                   2  38.0  161000.0          0
4                   0  40.0       NaN          1
5                   1  35.0  158000.0          1
6                   2   NaN  152000.0          0
7                   1  48.0  179000.0          1
8                   0  50.0  183000.0          0
9                   1  37.0  167000.0          1

## Stretch goal
`LabelEncoding` suggests a value difference between different classes. Instead, explore `OneHotEncoder` [OneHotEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) to produce categorical labels that are not biased:


In [0]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
cities_one_hot = OneHotEncoder().fit_transform(dataset[['Cities in East Bay']]).toarray()
print(cities_one_hot)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [0]:
cities = pd.DataFrame(cities_one_hot, columns=['Dublin', 'Pleasanton', 'Walnut Creek'], dtype=np.int64)

In [9]:
dataset = dataset.join([cities]).drop(['Cities in East Bay'], axis=1)
dataset

Age    Salary  Own Home?  Dublin  Pleasanton  Walnut Creek
0  44.0  172000.0          0       0           1             0
1  27.0  148000.0          1       0           0             1
2  30.0  154000.0          0       1           0             0
3  38.0  161000.0          0       0           0             1
4  40.0       NaN          1       1           0             0
5  35.0  158000.0          1       0           1             0
6   NaN  152000.0          0       0           0             1
7  48.0  179000.0          1       0           1             0
8  50.0  183000.0          0       1           0             0
9  37.0  167000.0          1       0           1             0